[package]
name = "flux-lang"
version = "0.1.0"
authors = ["Jonathan Vusich <31666175+JonathanVusich@users.noreply.github.com>"]
edition = "2018"

[toolchain]
channel = "nightly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"