[package]
name = "flux-lang"
version = "0.1.0"
authors = ["Jonathan Vusich <31666175+JonathanVusich@users.noreply.github.com>"]
edition = "2021"

[toolchain]
channel = "stable"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
bit-set = "0.5.2"
region = "3.0.0"

[dev-dependencies]
criterion = "0.3.5"

[profile.test]
opt-level=3

[[bench]]
name = "block_allocation"
harness = false

[[bench]]
name = "tagged_pointer"
harness = false

[[bench]]
name = "pointer"
harness = false