[package]
name = "krate"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
id = { path = "../id" }
interner = { path = "../interner" }

serde = "1.0.197"
radix_trie = "0.2.1"
