[package]
name = "concourse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
loom = "0.5"

[target.'cfg(loom)'.dependencies]
loom = "0.5"
