[package]
name = "concourse"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.4.0"
loom = "0.5"

[[bench]]
name = "contended_allocation"
harness = false

[target.'cfg(loom)'.dependencies]
loom = "0.5"
