[package]
name = "snap"
version = "0.1.0"
edition = "2021"

[dependencies]
snap_macro = { path = "../snap_macro" }
ron = { version = "0.8.1" }
serde = { version = "1.0.196", features = ["derive"] }

[dev-dependencies]
trybuild = "1.0.64"
