name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          override: true
      - name: Build Sinter
        run: cargo build --verbose
        working-directory: sinter-lang
      - name: Test Sinter
        run: cargo test --verbose
        working-directory: sinter-lang
      - name: Build Snap
        run: cargo build --verbose
        working-directory: snap
      - name: Test Snap
        run: cargo test --verbose
        working-directory: snap
      
